// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDaTp1XSUZjH23KnMbLunMz9QvKuLad9M8",
      authDomain: "match3-7093d.firebaseapp.com",
      databaseURL:
          "https://match3-7093d-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "match3-7093d",
      storageBucket: "match3-7093d.firebasestorage.app",
      messagingSenderId: "953843101514",
      appId: "1:953843101514:web:efea9a07b4cc0058851bb3",
      measurementId: "G-1XQWLTR3TF");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiebcYhx50L_7aIxhapzMuqXvOnK6bkM8',
    appId: '1:953843101514:android:3455b7817b52eba9851bb3',
    messagingSenderId: '123456789',
    projectId: 'match3-7093d',
    databaseURL:
        'https://match3-7093d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'match3-7093d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'match3-multiplayer',
    iosClientId: '123456789-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.match3',
    databaseURL: 'https://match3-multiplayer-default-rtdb.firebaseio.com',
    storageBucket: 'match3-multiplayer.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'match3-multiplayer',
    iosClientId: '123456789-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.match3',
    databaseURL: 'https://match3-multiplayer-default-rtdb.firebaseio.com',
    storageBucket: 'match3-multiplayer.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'match3-multiplayer',
    authDomain: 'match3-multiplayer.firebaseapp.com',
    databaseURL: 'https://match3-multiplayer-default-rtdb.firebaseio.com',
    storageBucket: 'match3-multiplayer.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );
}
